user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 512;
}

stream {
    map $ssl_preread_server_name $backend_addr {
        ozon.ru  127.0.0.1:8443;   # EE-TLS
        ""       127.0.0.1:8443;   # DD-Secure / empty SNI
        default  127.0.0.1:8444;   # redirect to site
    }

    server {
        listen 443;
        listen 3389;
        ssl_preread on;
        proxy_pass $backend_addr;
        proxy_connect_timeout 3s;
        proxy_timeout 3600s;
        proxy_buffer_size 16k;
    }
}

http {
    include      /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile     on;

    server {
        listen 8444 ssl;
        server_name _;
        ssl_certificate     /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        return 301 https://YOUR_SITE_DOMAIN$request_uri;
    }

    server {
        listen 80;
        server_name YOUR_DOMAIN;
        location /.well-known/acme-challenge/ { root /var/www/certbot; }
        location / { return 301 https://YOUR_SITE_DOMAIN$request_uri; }
    }
}
